trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  ConnectedServiceName: 'bd81ff36-5055-4fe5-905d-c299ef19f4cb'
  WebAppKind: 'webAppLinux'
  WebAppName: 'rbtest12'
  StartupCommand: 'java -jar /home/site/wwwroot/gs-spring-boot-0.1.0.jar --server.port=80'

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - task: Maven@3
      displayName: 'Maven app/pom.xml'
      inputs:
        mavenPomFile: 'app/pom.xml'
        codeCoverageToolOption: JaCoCo

    - task: CopyFiles@2
      displayName: 'Copy Files to: $(Build.ArtifactStagingDirectory)'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: '**/*.jar'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifact: drop'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'

- stage: Deploy
  dependsOn: Build
  jobs:
  - job: DeployJob
    steps:
    - download: current
      artifact: drop

    - task: AzureRmWebAppDeployment@4
      displayName: 'Deploy Azure App Service'
      inputs:
        azureSubscription: '$(ConnectedServiceName)'
        appType: '$(WebAppKind)'
        WebAppName: '$(WebAppName)'
        packageForLinux: '$(Pipeline.Workspace)/drop/app/target/gs-spring-boot-0.1.0.jar'
        RuntimeStack: 'TOMCAT|9.0-java11'
        StartupCommand: '$(StartupCommand)'
